"""Adding user_id column to Note

Revision ID: 481c46bf0ace
Revises: 
Create Date: 2023-11-27 12:59:31.546215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481c46bf0ace'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
